# Generated by Django 3.1 on 2022-12-10 07:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('body', models.CharField(max_length=500, verbose_name='Content')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, default='0000-00-00 00:00:00', verbose_name='Modified Date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('commenter', models.CharField(max_length=100, verbose_name='Comment by')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, default='0000-00-00 00:00:00', verbose_name='Modified Date')),
                ('blod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_post.post', verbose_name='Post')),
            ],
        ),
    ]
