# Generated by Django 3.1 on 2022-12-10 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Modified Date'),
        ),
    ]
