# Generated by Django 3.1 on 2022-12-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_auto_20221210_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blod',
            new_name='blog',
        ),
    ]
