# Generated by Django 3.1 on 2022-12-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_auto_20221210_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
    ]
